### PR TITLE
Allow arbitrary string exports

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
This PR includes two changes:
- `exports.package` (where `package` is a reserved word in strict mode) is now allowed.
  This seemed to be an arbitrary limitation, given that you can do `import { package as pkg } from "dep"` and that `exports.var` was already allowed.
- Allow arbitrary strings when doing `exports["foo bar"]`, rather than forcing the string contents to be an identifier. They can be imported in Node.js 16 using `import { "foo bar" as foobar } from "dep"`, or in older Node.js versions using `import * as ns from "dep"; ns["foo bar"]`.

I also refactored a bit how strings are parsed, by using a single `stringLiteral(quote)` function rather than having to branch between `'` and `"` every time.

Thanks @bmeck for [making me realize](https://twitter.com/bradleymeck/status/1385580080471056387) that they didn't work.

**TODO**:
- [x] Check how Babel compiles `export { x as "foo bar" }`, and make sure that it works. **EDIT**: Babel just generates `exports["foo bar"] = x;`.

### CODE REVIEW

**Review by guybedford — APPROVED** [review]
This seems ok to me. It's a shame we only got to this now as it's likely only 14+ at this point at best, but I'd be happy to release and backport if we have approval from others as well.

@bmeck can you provide your review here as well to confirm?

**Comment by bmeck** [comment]
this looks good to me. I'd actually be hesitant to port this to 14, since native won't support it.

**Review by bmeck — APPROVED** [review]

**Comment by guybedford** [comment]
@bmeck although` import * as m from 'cjs'`; m['...']` would work for Node.js 14, so perhaps still worthwhile for that at least? I'd like to at least keep the backports going as much as possible for future changes so would prefer not to maintain two separate branches here.

**Comment by guybedford** [comment]
Published in 1.2.0, will start porting now.

**Pull request merged**
